name: finpals
description: AI-powered personal finance & smart expense management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^13.2.0

  # Network
  dio: ^5.4.3
  connectivity_plus: ^6.0.3

  # Animation
  flutter_animate: ^4.5.0

  # Charts
  fl_chart: ^0.68.0

  # Auth
  google_sign_in: ^6.2.1
  flutter_secure_storage: ^9.0.0

  # Storage
  shared_preferences: ^2.2.3

  # Image
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1

  # WebView (Midtrans Snap)
  webview_flutter: ^4.7.0

  # Utils
  intl: ^0.19.0
  uuid: ^4.4.0
  crypto: ^3.0.3
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  permission_handler: ^11.3.1

  # UI extras
  shimmer: ^3.0.0
  lottie: ^3.1.0
  dotted_border: ^2.1.0
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
